package com.ekino.oss.metalastic.core

import kotlin.reflect.KType

/**
 * Terminal object field representing a self-referencing relationship in an Elasticsearch document.
 *
 * This class is automatically generated by the Metalastic annotation processor when a document or
 * object field references itself, either directly or through a complex type. Self-referencing
 * fields would create infinite recursion in the metamodel hierarchy, so they are terminated at this
 * point to maintain a safe, traversable type structure.
 *
 * ## When This Is Generated
 *
 * The processor generates a [SelfReferencingObject] when:
 * - A `@Document` class has a field of its own type
 * - An object field references its containing class
 * - Circular dependencies exist in the document structure
 *
 * ## Example Scenario
 *
 * ```kotlin
 * @Document(indexName = "category")
 * data class Category(
 *   @Field(type = FieldType.Keyword)
 *   val id: String,
 *
 *   @Field(type = FieldType.Text)
 *   val name: String,
 *
 *   @Field(type = FieldType.Object)
 *   val parentCategory: Category? // Self-reference
 * )
 * ```
 *
 * Generated metamodel:
 * ```kotlin
 * class QCategory<T : Any?>(
 *   parent: ObjectField<*>? = null,
 *   name: String = "",
 *   nested: Boolean = false,
 *   fieldType: KType
 * ) : Document<T>(...) {
 *
 *   @JvmField
 *   val id: KeywordField<String> = keywordField("id")
 *
 *   @JvmField
 *   val name: TextField<String> = textField("name")
 *
 *   // Terminates here to avoid infinite recursion
 *   @JvmField
 *   val parentCategory: SelfReferencingObject<Category?> =
 *     SelfReferencingObject(this, "parentCategory", false, typeOf<Category?>())
 * }
 * ```
 *
 * ## Usage
 *
 * You can still use the field for path construction and queries:
 * ```kotlin
 * val category = Metamodels.category
 * category.parentCategory.path() // Returns "parentCategory"
 * category.parentCategory.isNestedPath() // Works correctly
 * ```
 *
 * However, you cannot traverse further into the referenced type's properties since that would
 * require infinite nesting.
 *
 * @param T The type of the self-referencing field
 * @param parent The parent object field in the hierarchy
 * @param name The Elasticsearch field name
 * @param nested Whether this field is marked as nested in Elasticsearch
 * @param fieldType The Kotlin type information for runtime type safety
 * @see com.ekino.oss.metalastic.core.ObjectField
 * @see com.ekino.oss.metalastic.core.UnModellableObject
 */
class SelfReferencingObject<T : Any?>(
  parent: ObjectField<*>?,
  name: String,
  nested: Boolean = false,
  fieldType: KType,
) : ObjectField<T>(parent = parent, name = name, nested = nested, fieldType = fieldType)
