package com.metalastic.core

import kotlin.reflect.KType

/**
 * Terminal object field representing an unmodellable type in an Elasticsearch document.
 *
 * This class is automatically generated by the Metalastic annotation processor when it encounters a
 * field that cannot be fully modeled into a type-safe metamodel structure. This typically occurs
 * with complex generic types, collections without concrete element types, or types that don't have
 * a corresponding `@Document` or analyzable class definition.
 *
 * ## When This Is Generated
 *
 * The processor generates an [UnModellableObject] when:
 * - The field's target type cannot be resolved to a concrete class
 * - The field uses complex generics that cannot be statically analyzed
 * - The field references a type without `@Field` annotations
 * - The field's type is a collection with unknown element structure
 * - The type is from an external library without metamodel support
 *
 * ## Example Scenarios
 *
 * ### Dynamic/Generic Collections
 *
 * ```kotlin
 * @Document(indexName = "product")
 * data class Product(
 *   @Field(type = FieldType.Keyword)
 *   val id: String,
 *
 *   @Field(type = FieldType.Object)
 *   val metadata: Map<String, Any> // Cannot model arbitrary key-value pairs
 * )
 * ```
 *
 * ### External Types Without Metamodel
 *
 * ```kotlin
 * @Document(indexName = "order")
 * data class Order(
 *   @Field(type = FieldType.Keyword)
 *   val id: String,
 *
 *   @Field(type = FieldType.Object)
 *   val thirdPartyData: ExternalLibraryClass // No @Field annotations available
 * )
 * ```
 *
 * Generated metamodel:
 * ```kotlin
 * class QProduct<T : Any?>(
 *   parent: ObjectField<*>? = null,
 *   name: String = "",
 *   nested: Boolean = false,
 *   fieldType: KType
 * ) : Document<T>(...) {
 *
 *   @JvmField
 *   val id: KeywordField<String> = keywordField("id")
 *
 *   // Terminates here since Map<String, Any> structure is unknown at compile time
 *   @JvmField
 *   val metadata: UnModellableObject<Map<String, Any>> =
 *     UnModellableObject(this, "metadata", false, typeOf<Map<String, Any>>())
 * }
 * ```
 *
 * ## Usage
 *
 * You can still use the field for basic path construction:
 * ```kotlin
 * val product = Metamodels.product
 * product.metadata.path() // Returns "metadata"
 * product.metadata.isNestedPath() // Works correctly
 * ```
 *
 * However, you cannot traverse into the field's internal structure since the processor couldn't
 * generate a type-safe metamodel for it.
 *
 * @param T The type of the unmodellable field
 * @param parent The parent object field in the hierarchy
 * @param name The Elasticsearch field name
 * @param nested Whether this field is marked as nested in Elasticsearch
 * @param fieldType The Kotlin type information for runtime type safety
 * @see ObjectField
 * @see SelfReferencingObject
 */
class UnModellableObject<T : Any?>(
  parent: ObjectField<*>?,
  name: String,
  nested: Boolean = false,
  fieldType: KType,
) : ObjectField<T>(parent = parent, name = name, nested = nested, fieldType = fieldType)
